### ISSUE TITLE
Unicode mishandling

### ISSUE THREAD

**Issue by ToruiDev** [Daedo/Organization-XIII#1]
When the sigil happens to be an emoji e.g. 🤣 the generated names aren't rendered correctly. It's probably due to skin-tone modifiers or surrogate character pairs

**Comment by Daedo** [comment]
Should be solved with [the latest commit](https://github.com/Daedo/Organization-XIII/commit/ff52c4c2e96fbb8a1ed8acb46fe5e9a93e45fff6).
